# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import xai_service_pb2 as xai__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in xai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExplanationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExplanation = channel.unary_unary(
                '/Explanations/GetExplanation',
                request_serializer=xai__service__pb2.ExplanationsRequest.SerializeToString,
                response_deserializer=xai__service__pb2.ExplanationsResponse.FromString,
                _registered_method=True)
        self.ApplyAffectedActions = channel.unary_unary(
                '/Explanations/ApplyAffectedActions',
                request_serializer=xai__service__pb2.ApplyAffectedActionsRequest.SerializeToString,
                response_deserializer=xai__service__pb2.ApplyAffectedActionsResponse.FromString,
                _registered_method=True)
        self.GetFeatureImportance = channel.unary_unary(
                '/Explanations/GetFeatureImportance',
                request_serializer=xai__service__pb2.FeatureImportanceRequest.SerializeToString,
                response_deserializer=xai__service__pb2.FeatureImportanceResponse.FromString,
                _registered_method=True)
        self.RunExperimentHighlights = channel.unary_unary(
                '/Explanations/RunExperimentHighlights',
                request_serializer=xai__service__pb2.ExperimentRunsRequest.SerializeToString,
                response_deserializer=xai__service__pb2.ExperimentRunsResponse.FromString,
                _registered_method=True)


class ExplanationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetExplanation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyAffectedActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeatureImportance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunExperimentHighlights(self, request, context):
        """New RPC to run experiment highlights/clustering pipeline based on
        experiment runs data sent directly from the client (no files).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExplanationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetExplanation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExplanation,
                    request_deserializer=xai__service__pb2.ExplanationsRequest.FromString,
                    response_serializer=xai__service__pb2.ExplanationsResponse.SerializeToString,
            ),
            'ApplyAffectedActions': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyAffectedActions,
                    request_deserializer=xai__service__pb2.ApplyAffectedActionsRequest.FromString,
                    response_serializer=xai__service__pb2.ApplyAffectedActionsResponse.SerializeToString,
            ),
            'GetFeatureImportance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatureImportance,
                    request_deserializer=xai__service__pb2.FeatureImportanceRequest.FromString,
                    response_serializer=xai__service__pb2.FeatureImportanceResponse.SerializeToString,
            ),
            'RunExperimentHighlights': grpc.unary_unary_rpc_method_handler(
                    servicer.RunExperimentHighlights,
                    request_deserializer=xai__service__pb2.ExperimentRunsRequest.FromString,
                    response_serializer=xai__service__pb2.ExperimentRunsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Explanations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Explanations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Explanations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetExplanation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Explanations/GetExplanation',
            xai__service__pb2.ExplanationsRequest.SerializeToString,
            xai__service__pb2.ExplanationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyAffectedActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Explanations/ApplyAffectedActions',
            xai__service__pb2.ApplyAffectedActionsRequest.SerializeToString,
            xai__service__pb2.ApplyAffectedActionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeatureImportance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Explanations/GetFeatureImportance',
            xai__service__pb2.FeatureImportanceRequest.SerializeToString,
            xai__service__pb2.FeatureImportanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunExperimentHighlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Explanations/RunExperimentHighlights',
            xai__service__pb2.ExperimentRunsRequest.SerializeToString,
            xai__service__pb2.ExperimentRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
